import presetIcons from '@unocss/preset-icons';
import { defineConfig, presetWind3 } from 'unocss';

export default defineConfig({
	presets: [
		presetWind3(),
		presetIcons({
			extraProperties: {
				display: 'inline-block',
				'vertical-align': 'middle',
			},
		}),
	],
	shortcuts: {
		'app-shell': 'grid min-h-[100dvh] transition-[grid-template-columns] duration-220 ease',
		'brand-row': 'grid grid-cols-[48px_minmax(0,1fr)_44px] items-center gap-[12px]',
		'mark': 'grid h-[48px] w-[48px] place-items-center rounded-[16px] text-[12px] font-bold tracking-[0.08em]',
		'brand-title': 'm-0 text-[18px] font-extrabold leading-[1.15] tracking-[-0.01em]',
		'brand-subtitle': 'mb-0 mt-[4px] text-[13px]',
		'icon-button': 'grid h-[44px] w-[44px] cursor-pointer place-items-center rounded-[14px] border transition duration-140 ease',
		'ui-icon': 'h-[21px] w-[21px] shrink-0',
		'floating-menu': 'pointer-events-none fixed left-[18px] top-[18px] z-70 opacity-0 transition-[opacity,transform] duration-160 ease',
		'search': 'relative',
		'search-icon': 'pointer-events-none absolute left-[15px] top-1/2 h-[18px] w-[18px] -translate-y-1/2',
		'chapter-list': 'grid gap-[8px] overflow-auto pb-[8px] pr-[4px] -mb-[8px] -mr-[4px]',
		'chapter-button': 'grid w-full cursor-pointer grid-cols-[32px_minmax(0,1fr)] items-start gap-[10px] rounded-[16px] border border-transparent bg-transparent p-[12px] text-left transition duration-140 ease',
		'chapter-index': 'grid h-[32px] w-[32px] place-items-center rounded-[11px] text-[11px] font-bold tracking-[0.08em]',
		'chapter-name': 'block leading-[1.25] tracking-0',
		'chapter-meta': 'mt-[6px] flex flex-wrap gap-[6px] text-[12px] leading-[1.3]',
		'sidebar-note': 'mt-auto rounded-[18px] border border-dashed p-[12px] text-[13px]',
		'lesson-hero': 'relative mb-[18px] overflow-hidden',
		'breadcrumb': 'mb-[18px] flex flex-wrap items-center gap-[8px] text-[12px] font-bold uppercase tracking-[0.08em]',
		'lesson-title': 'relative z-1 m-0 max-w-[12ch] font-black leading-[1.02] tracking-[-0.025em] text-balance',
		'lesson-summary': 'relative z-1 mt-[18px] mb-0 max-w-[64ch]',
		'hero-meta': 'relative z-1 mt-[26px] flex flex-wrap gap-[10px]',
		'pill': 'inline-flex min-h-[34px] items-center gap-[8px] rounded-full border px-[11px] py-[7px] text-[13px] font-bold',
		'callout': 'my-[24px] grid grid-cols-[34px_minmax(0,1fr)] gap-[14px] rounded-[18px] border p-[18px]',
		'callout-mark': 'grid h-[34px] w-[34px] place-items-center rounded-[12px] text-[12px] font-extrabold tracking-[0.06em]',
		'code-block': 'relative my-[22px] overflow-hidden rounded-[18px] border',
		'code-title': 'flex min-h-[46px] items-center justify-between gap-[12px] py-[8px] pl-[16px] pr-[10px] text-[12px] tracking-[0.04em]',
		'copy-button': 'min-h-[34px] cursor-pointer rounded-full px-[11px] py-[6px] text-[12px] font-bold tracking-[0.02em]',
		'lesson-actions': 'mt-[18px] grid grid-cols-2 gap-[14px] p-[14px]',
		'nav-card': 'grid min-h-[76px] cursor-pointer content-center rounded-[18px] border p-[14px] text-left transition-[transform,box-shadow] duration-140 ease',
		'nav-kicker': 'mb-[4px] block text-[11px] tracking-[0.08em]',
		'nav-title': 'font-extrabold leading-[1.25]',
		'inspector': 'sticky grid h-fit self-start gap-[14px]',
		'inspector-card': 'p-[18px]',
		'inspector-title': 'mb-[12px] mt-0 text-[14px] font-extrabold uppercase tracking-[0.08em]',
		'progress-rail': 'h-[12px] w-full overflow-hidden rounded-full border',
		'progress-fill': 'block h-full w-0 rounded-full transition-[width] duration-120 ease-linear',
		'progress-text': 'mb-0 mt-[10px] text-[13px]',
		'goal-list': 'list-reset-grid',
		'todo-list': 'list-reset-grid',
		'list-reset-grid': 'm-0 grid list-none gap-[10px] p-0',
		'check-list-item': 'grid grid-cols-[18px_minmax(0,1fr)] items-start gap-[10px] text-[14px] leading-[1.45]',
		'dot': 'mt-[2px] h-[18px] w-[18px] rounded-full border-2',
		'todo-checkbox': 'mt-[2px] h-[18px] w-[18px]',
		'complete-button': 'min-h-[46px] w-full cursor-pointer rounded-full border font-extrabold tracking-[0.02em] transition-[transform,box-shadow] duration-140 ease',
		'empty-state': 'rounded-[16px] border border-dashed p-[16px] text-[14px]',
		'scrim': 'pointer-events-none fixed inset-0 z-30 opacity-0 transition-opacity duration-180 ease',
	},
});
